#!/usr/bin/env python3

""" Viki

Webhook reciever and automation framework

Usage:
    jobs
    job/<jobName>
    job/<jobName>/run

Maintainer:
    John Shanahan <shanahan.jrs@gmail.com>

License:
    Apache 2.0
    http://www.apache.org/licenses/LICENSE-2.0

Todo:
    - Add logging (replace the print statements with actual logging)
    - Add Auth
    - Make individual built dirs under .../jobs/<jobName>/<buildNumber>
    - Add funcs to count lastSuccessfulRun and lastFailedRun
    - Add Redis support
    - Create a routes file for all the api endpoints to be structured/organized
    - Testing

"""

### Imports

try:
    from flask import Flask, request, jsonify
    from lib.jobs import Jobs
    import json
    import redis
except ImportError as error:
    exit('ImportError: ' + str(error))


### Setup

# Classes
app = Flask(__name__)
job = Jobs()

# Viki globals
home_directory = "/usr/local/viki"
debug = True

# Redis
redis_host = ""
redis_port = 0000
redis_password = ""

redisconn = redis.Redis(
    host=redis_host,
    port=redis_port,
    password=redis_password
)


### Routes

@app.route("/")
def root():
    """ Home """
    return jsonify({"name":"viki", "version":"0.0.1"})

@app.route("/jobs")
def jobs():
    """ List all jobs """

    ret =  jsonify(job.getJobs())

    return ret

@app.route("/job/<string:jobName>", methods = ['GET', 'POST', 'PUT', 'DELETE'])
def get_job(jobName):
    """ Show single job details by name """
    ret = None

    if request.method == 'GET':
        # Retrieve a jobs details
        ret = job.get_job_by_name(jobName)

    if request.method == 'POST':
        # Requires "application/json" mime type and valid JSON body
        # containing description, and steps
        jobConfig = str(request.get_json())
        ret = job.create_job(jobName, jobConfig)

    if request.method == 'PUT':
        # Requires "application/json" mime type and valid JSON body
        # containing field/s to be updated
        ret = job.update_job(jobName)

    if request.method == 'DELETE':
        # Deletes a job from the repository
        ret = job.delete_job(jobName)

    if ret is None:
        ret = {"success":0, "message":"Failed"}

    return jsonify(ret)

@app.route("/job/<string:jobName>/run")
def run_job(jobName):
    """ Run specific job by name """
    return jsonify(job.run_job(jobName))


### Main

if __name__ == "__main__":

    if debug:
        app.debug = True

    app.run()